# assets:
#   favicon: assets/favicon.ico

project:
  type: website
  output-dir: docs

website:
title: "Adam Schroeder"
  navbar:
    background: transparent
    left:
      - href: index.qmd
      - text: Home

format:
  html:
    css: styles.css

# remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme
# markdown: kramdown
